language: go

services:
  - docker

go:
  - "1.10"

install:
  - go get -t -tags=integration ./...

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic -tags=integration

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
