language: go

services:
  - docker

go:
  - "1.15"

install:
  - go get -t ./...

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - go get github.com/mattn/goveralls
  - goveralls -coverprofile=coverage.txt

notifications:
  email: false
